### PR TITLE
bump go version to 1.17

### PR DESCRIPTION
**Pull request by ex-preman**
add go.sum to pass golangci-lint typecheck

### CODE REVIEW

**Comment by ex-preman** [comment]
if the library doesn't have go.sum it will make golangci-lint typecheck always fail, and my company use that as standard linter

**Comment by gen2brain** [comment]
Ok, but that looks like a hack. If you do here `go mod init`, followed by `tidy` one only gets `go.mod`, without `go.sum` because there are no 3rdparty packages. That tool should actually be fixed to not unconditionally demand that `go.sum` must exist.

Anyway, I will include the hack, but what about that version bump, why is that needed? Can you revert it so I can just commit the empty file?

**Comment by ex-preman** [comment]
for the version bump because bitbucket-pipeline doesn't support Go version below 1.17. I tried 1.16 but still failed, it succeeded in using 1.17, even in their articles said they support the latest 1.16 but it's not :( 

here is the reference: https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-Bitbucket-API-Requires-Latest-Version-of-Go/ba-p/1975819

if you don't want it I can fork it somehow.

**Comment by gen2brain** [comment]
Ok, I guess it is fine, anyway as I remember only the last two versions are supported, and now we are at 1.19. It is just that there are still many people who for whatever reason use older versions. I will do tag new version soon.

**Pull request merged**
