### PR TITLE
Update fitz.go

### PR DESCRIPTION
**Pull request by HaywardShen**
fix memory leakage

### CODE REVIEW

**Comment by gen2brain** [comment]
@HaywardShen Can you please change `C.free(unsafe.Pointer(pixels))` with `fz_drop_pixmap`? There is already a dedicated function for that. Thanks.

**Comment by gen2brain** [comment]
Ahh, sorry, it is pixels, not pixmap.

**Comment by gen2brain** [comment]
Merged, thanks!

**Comment by HaywardShen** [comment]
It would be great to help!

**Pull request merged**
